#!/usr/bin/env bash
# deployments/scripts/generate-notices.sh — 聚合生成 THIRD_PARTY_NOTICES.md（决策书 §6.1）
#
# 从 third-party/lock.json 与 third-party/NOTICES/ 聚合生成根目录 THIRD_PARTY_NOTICES.md。
# 幂等：重复运行结果一致。不依赖外部网络。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOCK_FILE="$REPO_ROOT/third-party/lock.json"
OUT_FILE="$REPO_ROOT/THIRD_PARTY_NOTICES.md"

if ! command -v jq >/dev/null 2>&1; then
  echo "✗ generate-notices: jq 未安装（必需）" >&2
  exit 1
fi
if [[ ! -f "$LOCK_FILE" ]]; then
  echo "✗ lock.json 不存在：$LOCK_FILE" >&2
  exit 1
fi

project=$(jq -r '.project // "mora"' "$LOCK_FILE")
project_license=$(jq -r '.project_license // "Apache-2.0"' "$LOCK_FILE")
components=$(jq -r '.components | length' "$LOCK_FILE")

{
  echo "# Third-Party Notices"
  echo
  echo "This file is generated by \`make notices\` from \`third-party/lock.json\` and the"
  echo "per-component NOTICE files under \`third-party/NOTICES/\`. It lists the"
  echo "third-party components ${project} references, along with their licenses and NOTICE"
  echo "text, for distribution compliance."
  echo
  echo "${project^} itself is licensed under the ${project_license} license"
  echo "(see \`LICENSE\`)."
  echo
  echo "Phase 0 scope (per \`design-docs/13-phase0-contract-safety-baseline.md\` §6):"
  echo "this manifest fixes the **reference baselines** only. No third-party runtime"
  echo "dependency is shipped yet; the entries below are pinned baselines that future"
  echo "selections (Phase 1 / Phase 3) must extend through the ADR + lockfile + digest"
  echo "process."
  echo
  echo "---"
  echo

  if [[ "$components" -eq 0 ]]; then
    echo "_No third-party components pinned yet._"
  fi

  for i in $(seq 0 $((components - 1))); do
    idx="components[$i]"
    name=$(jq -r ".$idx.name // empty" "$LOCK_FILE")
    version=$(jq -r ".$idx.version // empty" "$LOCK_FILE")
    ecosystem=$(jq -r ".$idx.ecosystem // empty" "$LOCK_FILE")
    source_url=$(jq -r ".$idx.source_url // empty" "$LOCK_FILE")
    source_repo_url=$(jq -r ".$idx.source_repo_url // empty" "$LOCK_FILE")
    digest=$(jq -r ".$idx.commit_sha_or_digest // empty" "$LOCK_FILE")
    digest_algo=$(jq -r ".$idx.digest_algorithm // empty" "$LOCK_FILE")
    license=$(jq -r ".$idx.license // empty" "$LOCK_FILE")
    notice_path=$(jq -r ".$idx.notice_path // empty" "$LOCK_FILE")
    capability=$(jq -r ".$idx.capability // empty" "$LOCK_FILE")
    status=$(jq -r ".$idx.status // empty" "$LOCK_FILE")
    adr=$(jq -r ".$idx.adr // empty" "$LOCK_FILE")
    comment=$(jq -r ".$idx.comment // empty" "$LOCK_FILE")

    heading="$name"
    [[ -n "$ecosystem" || -n "$version" ]] && heading="$name ($([ -n "$ecosystem" ] && echo "$ecosystem")$([ -n "$ecosystem" ] && [ -n "$version" ] && echo " ")$([ -n "$version" ] && echo "$version"))"
    echo "## $((i+1)). $heading"
    echo
    [[ -n "$source_url" ]] && { echo "- **Source:** $source_url"; }
    [[ -n "$source_repo_url" ]] && echo "- **Repository:** $source_repo_url"
    [[ -n "$digest" ]] && echo "- **Commit / digest:** \`$digest\`$([ -n "$digest_algo" ] && echo " ($digest_algo)")"
    [[ -n "$license" ]] && echo "- **License:** $license"
    [[ -n "$capability" ]] && echo "- **Capability:** $capability"
    [[ -n "$status" ]] && echo "- **Status:** $status"
    [[ -n "$adr" ]] && echo "- **ADR:** \`$adr\`"
    [[ -n "$comment" ]] && echo "- **Comment:** $comment"
    echo

    if [[ -n "$license" ]]; then
      echo "### $license"
      echo
      if [[ -n "$notice_path" && -f "$REPO_ROOT/$notice_path" ]]; then
        echo '```'
        cat "$REPO_ROOT/$notice_path"
        echo '```'
      else
        echo "_(NOTICE file missing at $notice_path — run \`make third-party-check\` to fail-closed.)_"
      fi
      echo
    fi
    echo "---"
    echo
  done
} > "$OUT_FILE"

echo "✓ 生成 $OUT_FILE（$components 个组件）"
